/** PRD 2.4: offer, counter-offer and acceptance endpoints. */
import { Body, Controller, Param, Post, Req, ForbiddenException, NotFoundException, BadRequestException } from '@nestjs/common';
import { DataStore } from '../infra/data.store';
import { Roles } from '../common/decorators/roles.decorator';
@Controller('api/app')
export class OffersController {
  constructor(private readonly data: DataStore) {}
  @Roles('helper', 'both') @Post('tasks/:taskId/offers') create(@Req() req: any, @Param('taskId') taskId: string, @Body() body: any) { const task = this.data.tasks.find(t => t.id === taskId); if (!task) throw new NotFoundException('TASK_NOT_FOUND'); if (task.posterId === req.user.sub) throw new ForbiddenException('CANNOT_OFFER_ON_OWN_TASK'); const amount = Number(body.amount); if (!Number.isFinite(amount) || amount <= 0) throw new BadRequestException('INVALID_OFFER_AMOUNT'); const existing = this.data.offers.find(o => o.taskId === taskId && o.helperId === req.user.sub && ['submitted', 'countered'].includes(o.status)); if (existing) throw new BadRequestException('OFFER_ALREADY_SENT'); const offer = { id: this.data.id(), taskId, helperId: req.user.sub, helperName: req.user.sub, amount, message: String(body.message || ''), status: 'submitted', createdAt: new Date().toISOString() }; task.offers.push(offer); this.data.offers.push(offer); return { offer, task, notifications: [] }; }
  @Roles('poster', 'both') @Post('offers/:offerId/accept') accept(@Req() req: any, @Param('offerId') offerId: string) { const offer = this.data.offers.find(o => o.id === offerId); if (!offer) throw new NotFoundException('OFFER_NOT_FOUND'); const task = this.data.tasks.find(t => t.id === offer.taskId); if (!task || task.posterId !== req.user.sub) throw new ForbiddenException('FORBIDDEN'); this.data.offers.filter(o => o.taskId === task.id && o.id !== offer.id && o.status === 'submitted').forEach(o => o.status = 'declined'); offer.status = 'accepted'; task.status = 'awaiting_payment'; return { offer, task, notifications: [] }; }
  @Roles('poster', 'both') @Post('tasks/:taskId/offers/:offerId/accept') acceptTaskOffer(@Req() req: any, @Param('offerId') offerId: string) { return this.accept(req, offerId); }
  @Post('offers/:offerId/counter') counter(@Req() req: any, @Param('offerId') offerId: string, @Body() body: any) { const offer = this.data.offers.find(o => o.id === offerId); if (!offer) throw new NotFoundException('OFFER_NOT_FOUND'); const amount = Number(body.amount); if (!Number.isFinite(amount) || amount <= 0) throw new BadRequestException('INVALID_OFFER_AMOUNT'); const next = { ...offer, id: this.data.id(), amount, message: String(body.message || ''), status: 'countered', parentOfferId: offer.id, createdBy: req.user.sub, createdAt: new Date().toISOString() }; this.data.offers.push(next); return { offer: next, task: this.data.tasks.find(t => t.id === offer.taskId), notifications: [] }; }
  @Post('tasks/:taskId/offers/:offerId/counter') counterTaskOffer(@Req() req: any, @Param('offerId') offerId: string, @Body() body: any) { return this.counter(req, offerId, body); }
}
