import { Body, Controller, Get, Post, Req } from '@nestjs/common'; import { Public } from './common/decorators/public.decorator'; import { RedisService } from './infra/redis.service'; import { DataStore } from './infra/data.store';
@Controller('api') export class AppController {
  constructor(private readonly redis: RedisService, private readonly data: DataStore) { }
  @Public() @Get('health') health() { return { ok: true, service: 'australian-helper-server', time: new Date().toISOString() }; }
  @Public() @Get('app/config') config() { return { appConfig: { appName: 'Australian Helper', environment: 'local', maintenanceMode: false, minimumSupportedVersion: '1.0.0', latestVersion: '1.0.0', antiRobot: { provider: 'cloudflare-turnstile', enabled: false, enforced: false, siteKey: '', challengeUrl: '', actions: [] }, theme: { primary: '#0F756D', primaryDark: '#0A544F', accent: '#F2A014', background: '#F5FAFA' }, home: { eyebrow: 'AUSTRALIAN HELPER', title: 'A cleaner way to get local help.', subtitle: 'Post a task, compare trusted offers, choose your Helper, then keep everything in one safe thread.', primaryButton: 'Post a Task', secondaryButton: 'Browse Tasks', categoryTitle: 'Popular categories', categorySubtitle: 'Fast entry points for common Australian Helper jobs' }, onboarding: { showOnboarding: true, title: 'A cleaner way to get local help.', subtitle: 'Post a task, compare trusted offers, choose your Helper, then keep everything in one safe thread.' }, featureFlags: { stripePayments: true, pushNotifications: true, chat: true }, support: { email: 'australianshelper@gmail.com', phone: '+61 400 000 000', hours: 'Mon-Fri 9:00-17:00 AEST' } }, categories: ['Cleaning', 'Gardening', 'Delivery', 'Handyman', 'Moving', 'Tutoring', 'Design', 'Others'], supportedLanguages: [{ code: 'en', appValue: 'en', shortTitle: 'EN', title: 'English', locale: 'en-AU' }], categoryTranslations: {}, updatedAt: new Date().toISOString() }; }
  @Public() @Get('app/state') state() { return { users: this.data.users.map((user) => ({ id: user.id, name: user.name, email: user.email, role: user.role, suburb: '', bio: '', phone: '', skills: [], createdAt: user.createdAt })), helpers: [], tasks: this.data.tasks.map((task) => ({ ...task, state: 'VIC', date: task.createdAt.slice(0, 10), time: '', createdBy: task.posterId, offers: task.offers || [], photos: [] })), taskReviews: [], rewardLedger: [], notifications: [], threads: [], categories: ['Cleaning', 'Gardening', 'Delivery', 'Handyman', 'Moving', 'Tutoring', 'Design', 'Others'], supportedLanguages: [{ code: 'en', appValue: 'en', shortTitle: 'EN', title: 'English', locale: 'en-AU' }], categoryTranslations: {}, updatedAt: new Date().toISOString() }; }
  @Public() @Get('health/dependencies') dependencies() { return { database: { configured: Boolean(process.env.DATABASE_URL), mode: process.env.DATABASE_URL ? 'migration-ready' : 'memory' }, redis: { configured: this.redis.configured, available: this.redis.available, error: this.redis.error }, stripe: { configured: Boolean(process.env.STRIPE_SECRET_KEY), webhookConfigured: Boolean(process.env.STRIPE_WEBHOOK_SECRET), mode: process.env.STRIPE_SECRET_KEY ? 'live-sdk' : 'mock' }, expoPush: { configured: Boolean(process.env.EXPO_ACCESS_TOKEN), enabled: process.env.EXPO_PUSH_ENABLED === 'true', mode: process.env.EXPO_PUSH_ENABLED === 'true' ? 'expo' : 'mock' }, chat: { transport: 'websocket+rest', paymentGate: process.env.CHAT_ALLOW_PREPAYMENT === 'true' || process.env.CHAT_REQUIRE_PAYMENT === 'false' ? 'disabled' : 'enabled', pushOnMessage: true } }; }
  @Post('app/notifications/read') readNotifications(@Req() req: any, @Body() body: any) { return { ok: true, updated: body?.all ? 0 : (body?.ids || []).length, state: null }; }
  @Post('app/profile-media/report') reportProfileMedia(@Req() req: any, @Body() body: any) { return { ok: true, duplicate: false, report: { id: this.data.id(), reporterUserId: req.user.sub, targetUserId: body?.targetUserId, mediaType: body?.mediaType, reason: body?.reason, details: body?.details, status: 'queued', createdAt: new Date().toISOString() }, state: null }; }
  @Post('app/membership/pro/google-play') membership(@Req() req: any, @Body() body: any) { const user: any = this.data.users.find(item => item.id === req.user.sub); if (user) { user.membershipType = 'pro'; user.proStatus = 'active'; user.subscriptionProvider = 'google_play'; user.subscriptionGooglePlayProductId = body?.productId; user.subscriptionGooglePlayTransactionId = body?.transactionId; } return { user: user || null, notifications: [], state: null }; }
  @Post('app/payout/refresh') payoutRefresh(@Req() req: any) { const user: any = this.data.users.find(item => item.id === req.user.sub); if (user) user.bankVerified = Boolean(user.bankVerified); return { ok: true, account: { payoutStatus: user?.bankVerified ? 'enabled' : 'pending', bankVerified: Boolean(user?.bankVerified), payoutsEnabled: Boolean(user?.bankVerified) }, user: user || null, state: null }; }
}
